### ISSUE TITLE
Whitesource scan of Actio components/dependencies

### ISSUE THREAD

**Issue by JustusOrtlepp** [mojaloop/fraud_risk_management#201]
**As a** platform operator,
**I want** to ensure that the open source components and tools used by Actio as dependencies do not introduce any vulnerabilities to the platform
**So that** I can be assured that the platform is secure.

WhiteSource scan requested by the Mojaloop Foundation, facilitated by Crosslake.

**Comment by elnyry-sam-k** [comment]
Not applicable anymore; moved to Tazama
