### ISSUE TITLE
[USER STORY] Source data preservation

### ISSUE THREAD

**Issue by JustusOrtlepp** [mojaloop/fraud_risk_management#24]
## Story Title
**As a** Mojaloop FRM operator, **I want to** record the data I received through the ingestion interface in its original, raw format prior to any data preparation processing, **so that** I am able to account for any changes made to the data within the system since receiving the data **and so that** I am able to revert data back to its original state, if needed **and so that** I am able to monitor the data quality performance of the data originator **and so that** I am able to retroactively apply any changes to the data preparation processing to the original data, if needed.

## Acceptance criteria
1. **Given** (context) **and** (more context) **when** (event) **then** (outcome) **and** (another outcome)...

**Comment by elnyry-sam-k** [comment]
Not applicable anymore; moved to Tazama
