### ISSUE TITLE
[USER STORY] RE - Access to historical data

### ISSUE THREAD

**Issue by JustusOrtlepp** [mojaloop/fraud_risk_management#70]
## Story Title
**As a** Mojaloop FRM Operator, **I want** the rules engine to have access to historical transactional data, **so that** I can evaluate the fraud risk for new transactions where the fraud risk typology relies on the evaluation of historical trends in the data

## Acceptance criteria
1. **Given** (context) **and** (more context) **when** (event) **then** (outcome) **and** (another outcome)...

**Comment by elnyry-sam-k** [comment]
Not applicable anymore; moved to Tazama
