### ISSUE TITLE
[USER STORY] RE - Rules classification for performance

### ISSUE THREAD

**Issue by JustusOrtlepp** [mojaloop/fraud_risk_management#77]
## Story Title
**As a** Mojaloop FRM operator, **I want to** classify rules according to their urgency, **so that** rules that are urgent can be evaluated "in line" with the transaction in real-time and rules that are less urgent or not urgent can be deferred and evaluated in near-real time **so that** I can manage performance without unlimited dynamic hardware scaling at great cost.

## Acceptance criteria
1. **Given** (context) **and** (more context) **when** (event) **then** (outcome) **and** (another outcome)...

**Comment by elnyry-sam-k** [comment]
Not applicable anymore; moved to Tazama
