### ISSUE TITLE
[USER STORY] Build the entity resolution engine

### ISSUE THREAD

**Issue by JustusOrtlepp** [mojaloop/fraud_risk_management#94]
## Story Title
**As a** Fraud Risk Manager,
**I want to** uniquely identify each customer in the eco-system,
**so that** I can unify multiple versions of the same customer as they appear through-out the network into a single customer view 
**and so that** I can assign a unique identifier to each customer

## Acceptance criteria
1. Verify that a collection of data is identified as either belonging to a known customer and
a. assign the existing UUID to the transaction Payer or Payee or
b. issue a new UUID to the customer data set and assign the new UUID to the transaction Payer or Payee
2. Verify that a probability score is assigned to the strength of the match to an existing UUID
3. Verify that a probability score is assigned to the strength of a mismatch to a new UUID
4. Verify that an alert has been generated to a system operator for a match that falls within the ambiuity thresholds for a match

**Comment by elnyry-sam-k** [comment]
Not applicable anymore; moved to Tazama
